apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollama-stack.fullname" . }}-ui
  labels:
    {{- include "ollama-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: tiny-ollama-ui
spec:
  type: {{ .Values.tinyOllamaUI.service.type }}
  ports:
    - port: {{ .Values.tinyOllamaUI.service.port }}
      targetPort: {{ .Values.tinyOllamaUI.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "ollama-stack.tinyOllamaUI.selectorLabels" . | nindent 4 }}
