apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollama-stack.fullname" . }}-ollama
  labels:
    {{- include "ollama-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
    - port: {{ .Values.ollama.service.port }}
      targetPort: {{ .Values.ollama.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "ollama-stack.ollama.selectorLabels" . | nindent 4 }}
